[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/var/task/src/score_360_flow_to_s3.py", line 178, in lambda_handler
    header = data.read(100).decode('utf-8')

[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte Traceback (most recent call last):   File "/var/task/src/score_360_flow_to_s3.py", line 178, in lambda_handler     header = data.read(100).decode('utf-8')
